### ISSUE TITLE
Deleted scenario results in permanently deployed lance

### ISSUE THREAD

**Issue by TheSilentK21** [MegaMek/mekhq#2791]
### Environment
MekHQ v49.2
Win 10 Home
Java 11.0.11 2021-04-20

### Description
A generated scenario (Destroy Grounded Dropship) was accidentally GM-mode removed instead of manually completed. The lance assigned to the scenario remained deployed, and is unable to be undeployed or removed via the dropdown menu in the TO&E tab. ("Undeploy" appears functional but has no effect, "Remove" is gray and unselectable). This condition persists even if the contract is completed. By dragging the lance to a different sub-unit in the TO&E it becomes undeployed and removable as normal, but the enemy force is still unselectable.

The Campaign State tab map hex with the enemy force (3,3) is not selectable by clicking on it.

Loading an earlier save, deploying the same lance via TO&E or Campaign State and removing the scenario does not recreate the error.

![Screenshot (54)](https://user-images.githubusercontent.com/86847410/128213275-7e55e232-4d53-4340-b672-a33ea5aa7a4a.png)

### Files
[Fighting Bulldogs30491230 pre bug.cpnx.gz](https://github.com/MegaMek/mekhq/files/6932636/Fighting.Bulldogs30491230.pre.bug.cpnx.gz) 
The scenario available for deployment as normal in the Briefing Room tab.

[Fighting Bulldogs30491231 cmd lance bugged.cpnx.gz](https://github.com/MegaMek/mekhq/files/6932638/Fighting.Bulldogs30491231.cmd.lance.bugged.cpnx.gz) 
The scenario deleted and command lance behaving abnormally

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6932648/mekhqlog.txt)
[AllMyCustoms8-4-21.zip](https://github.com/MegaMek/mekhq/files/6932656/AllMyCustoms8-4-21.zip)

**Comment by NickAragua** [comment]
The show-stopping behavior should no longer be occurring in the nightly builds (or 49.3 when it comes out). However, currently, gm-removing a scenario from here will result in a phantom scenario remaining on the stratcon map if there's also an allied facility there, which should probably be addressed at some point post 49.3

**Comment by mjbroekman** [comment]
I can confirm that this is still an issue in 0.49.7. I deleted a scenario that was buggy (it would hang during turn 1 movement for the opfor bot) and the lances I had deployed for that are still deployed, months later.
